In [7]:
import matplotlib.pyplot as plt
import numpy as np
import keras
from keras.layers import Conv2D, MaxPool2D, Flatten
from keras.layers import Dense, Dropout
#from xgboost import XGBClassifier
import seaborn as sn
from sklearn.metrics import accuracy_score
import log
import tensorflow as tf
from read_images_tf_colab import ReadImages

2019-09-03 21:24:07,977 - INFO - read_images_tf_colab - Reading Data File : sign_mnist_train.csv
2019-09-03 21:24:07,977 - INFO - read_images_tf_colab - Reading Data File : sign_mnist_train.csv
2019-09-03 21:24:07,977 - INFO - read_images_tf_colab - Reading Data File : sign_mnist_train.csv
I0903 21:24:07.977059 140567199917952 read_images_tf_colab.py:132] Reading Data File : sign_mnist_train.csv


(24709, 28, 28, 1)
(24709,)


In [0]:
logger = log.setup_custom_logger('CNN-Images')
def run_model_cnn(train_images, train_labels, test_images, test_labels):


	
	train_labels = keras.utils.np_utils.to_categorical(train_labels)
	test_labels = keras.utils.np_utils.to_categorical(test_labels)

	model = keras.models.Sequential([
		#32 5x5 subregions
	    keras.layers.Conv2D(32, (3, 3), padding="same", input_shape=[28, 28, 1]),
	    #2x2 pool with with stripe of two so they don't overlap
	    keras.layers.MaxPool2D((2,2)),
	    #64 5x5 filters
	    keras.layers.Conv2D(64, (3, 3), padding="same"),
	    #pool again
	    keras.layers.MaxPool2D((2,2)),
	    #flatten before dense layer
	    keras.layers.Flatten(),
	    #dense neuron layer
	    keras.layers.Dense(1024, activation='relu'),
	    keras.layers.Dropout(0.5),
	    #dense layer for output
	    keras.layers.Dense(25, activation='softmax')
	])
	# model = keras.models.Sequential()
	# model.add(keras.layers.Conv2D(32, (3,3), padding='same', activation='relu', input_shape=(28, 28, 1,)))
	# model.add(keras.layers.Conv2D(64, (3,3), padding='same', activation='relu'))
	# model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
	# model.add(keras.layers.Dropout(0.3))
	# model.add(keras.layers.Conv2D(128, (3,3), padding='same', activation='relu'))
	# model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
	# model.add(keras.layers.Conv2D(128, (2,2), padding='same', activation='relu'))
	# model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
	# model.add(keras.layers.Dropout(0.3))
	# model.add(keras.layers.Flatten())
	# model.add(keras.layers.Dense(1500, activation='relu'))
	# model.add(keras.layers.Dropout(0.5))
	# model.add(keras.layers.Dense(25, activation='softmax'))
	
	model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
	model.fit(train_images, train_labels, validation_split=0.5, batch_size=64, epochs=5, verbose=True)
	test_loss, test_accuracy = model.evaluate(test_images, test_labels, verbose=0)
	print("Loss : {}".format(test_loss))
	print("Accuracy : {}".format(test_accuracy))
	logger.info("Running Prediction")
	predictions = model.predict_classes(test_images)
	logger.debug("Making Confusion Matrix")

In [0]:
image_reader = ReadImages()
data_dir = 'sign_mnist_train.csv'

#train_images, test_images, train_labels, test_labels = image_reader.process_image_wrapper(data_dir)
train_images, test_images, train_labels, test_labels, feature_names = image_reader.read_pixel_csv(data_dir, test_train_split=0.01, reshape=True)

logger.info("Train Image Shape : {}".format(train_images.shape))
logger.info("Test Image Shape : {}".format(test_images.shape))
logger.info("Train Label Shape : {}".format(train_labels.shape))
logger.info("Train Label Shape : {}".format(test_labels.shape))


print(train_images[0])

run_model_cnn(train_images, train_labels, test_images, test_labels)

2019-09-03 21:25:53,903 - INFO - read_images_tf_colab - Reading Data File : sign_mnist_train.csv
2019-09-03 21:25:53,903 - INFO - read_images_tf_colab - Reading Data File : sign_mnist_train.csv
2019-09-03 21:25:53,903 - INFO - read_images_tf_colab - Reading Data File : sign_mnist_train.csv
I0903 21:25:53.903496 140567199917952 read_images_tf_colab.py:132] Reading Data File : sign_mnist_train.csv
2019-09-03 21:25:57,247 - INFO - <ipython-input-11-60f9844f14cd> - Train Image Shape : (27180, 28, 28, 1)
2019-09-03 21:25:57,247 - INFO - <ipython-input-11-60f9844f14cd> - Train Image Shape : (27180, 28, 28, 1)
I0903 21:25:57.247517 140567199917952 <ipython-input-11-60f9844f14cd>:7] Train Image Shape : (27180, 28, 28, 1)
2019-09-03 21:25:57,250 - INFO - <ipython-input-11-60f9844f14cd> - Test Image Shape : (275, 28, 28, 1)
2019-09-03 21:25:57,250 - INFO - <ipython-input-11-60f9844f14cd> - Test Image Shape : (275, 28, 28, 1)
I0903 21:25:57.250346 140567199917952 <ipython-input-11-60f9844f14cd>:8

[[[0.74509804]
  [0.75294118]
  [0.76862745]
  [0.78431373]
  [0.78823529]
  [0.78431373]
  [0.79607843]
  [0.80784314]
  [0.81960784]
  [0.82745098]
  [0.82745098]
  [0.83529412]
  [0.84313725]
  [0.84705882]
  [0.85098039]
  [0.85490196]
  [0.85882353]
  [0.85882353]
  [0.85882353]
  [0.8627451 ]
  [0.8627451 ]
  [0.85882353]
  [0.85490196]
  [0.85490196]
  [0.85490196]
  [0.85882353]
  [0.85098039]
  [0.84705882]]

 [[0.74509804]
  [0.75294118]
  [0.76862745]
  [0.78431373]
  [0.79215686]
  [0.79215686]
  [0.8       ]
  [0.81176471]
  [0.81568627]
  [0.82745098]
  [0.83529412]
  [0.83921569]
  [0.84705882]
  [0.85490196]
  [0.85882353]
  [0.85490196]
  [0.85882353]
  [0.85882353]
  [0.8627451 ]
  [0.86666667]
  [0.8627451 ]
  [0.8627451 ]
  [0.85882353]
  [0.85882353]
  [0.85882353]
  [0.85882353]
  [0.85882353]
  [0.85490196]]

 [[0.74509804]
  [0.76078431]
  [0.77254902]
  [0.78823529]
  [0.79215686]
  [0.79607843]
  [0.81176471]
  [0.81568627]
  [0.82352941]
  [0.83137255]
  [0.8

W0903 21:25:57.480443 140567199917952 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3576: The name tf.log is deprecated. Please use tf.math.log instead.

W0903 21:25:57.623357 140567199917952 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 13590 samples, validate on 13590 samples
Epoch 1/5
13590/13590 [==============================] - 33s 2ms/step - loss: 1.2528 - acc: 0.6232 - val_loss: 0.2328 - val_acc: 0.9345
Epoch 2/5
13590/13590 [==============================] - 32s 2ms/step - loss: 0.1295 - acc: 0.9642 - val_loss: 0.0203 - val_acc: 0.9987
Epoch 3/5
12736/13590 [===========================>..] - ETA: 1s - loss: 0.0346 - acc: 0.9918